-- Seed data for knowledge bases
-- This is a simplified version. In production, these would be full documents with embeddings

-- Base 1: Ganchos
INSERT INTO knowledge_documents (base_type, title, content, metadata) VALUES
('ganchos', 'Gancho: Perda de dinheiro', 'Você já perdeu dinheiro sem saber por quê? Descubra o erro silencioso que está dilapidando seu patrimônio.', '{"tipo": "medo", "canal": "instagram", "intencao": "parada"}'),
('ganchos', 'Gancho: Inflação', 'A inflação está comendo seu dinheiro e você nem percebeu. Veja o cálculo assustador.', '{"tipo": "medo", "canal": "instagram", "intencao": "educacao"}'),
('ganchos', 'Gancho: Primeiro milhão', 'Como chegar ao primeiro milhão sem ser herdeiro: o passo a passo que ninguém te conta.', '{"tipo": "desejo", "canal": "instagram", "intencao": "inspiracao"}'),
('ganchos', 'Gancho: Aposentadoria', 'Sua aposentadoria do INSS vai dar quanto? A resposta pode te assustar.', '{"tipo": "medo", "canal": "instagram", "intencao": "parada"}'),
('ganchos', 'Gancho: Independência financeira', 'O dia que parei de depender do salário: como construir renda passada de verdade.', '{"tipo": "desejo", "canal": "instagram", "intencao": "inspiracao"}'),
('ganchos', 'Gancho: Erros comuns', '3 erros que todo iniciante comete no primeiro investimento (e como evitar).', '{"tipo": "curiosidade", "canal": "instagram", "intencao": "educacao"}'),
('ganchos', 'Gancho: Reserva de emergência', 'Por que sua reserva de emergência está no lugar errado (e isso está te custando dinheiro).', '{"tipo": "curiosidade", "canal": "instagram", "intencao": "educacao"}'),
('ganchos', 'Gancho: Imposto de renda', 'Você está pagando mais imposto do que deveria? Descubra em 1 minuto.', '{"tipo": "curiosidade", "canal": "instagram", "intencao": "utilidade"}'),
('ganchos', 'Gancho: Diversificação', 'Não coloque todos os ovos na mesma cesta: o que significa diversificar na prática.', '{"tipo": "educacao", "canal": "instagram", "intencao": "educacao"}'),
('ganchos', 'Gancho: Tesouro Direto vs CDB', 'Tesouro Direto ou CDB: onde seu dinheiro rende mais? A resposta vai surpreender.', '{"tipo": "comparacao", "canal": "instagram", "intencao": "utilidade"}'),
('ganchos', 'Gancho: Planejamento financeiro', 'Como organizar suas finanças em 2025: o guia que você precisava no começo do ano.', '{"tipo": "utilidade", "canal": "instagram", "intencao": "utilidade"}'),
('ganchos', 'Gancho: Dívidas', 'Pagar dívidas ou investir? A matemática que vai mudar sua decisão.', '{"tipo": "dilema", "canal": "instagram", "intencao": "educacao"}');

-- Base 2: Estratégia de conteúdo
INSERT INTO knowledge_documents (base_type, title, content, metadata) VALUES
('estrategia', 'Princípio: Funil de conteúdo', 'Todo conteúdo deve ter funil claro: ATRAÇÃO (trazer novo público) → NUTRIÇÃO (educar e aquecer) → CONVERSÃO (transformar em cliente). Nunca crie conteúdo sem saber em qual etapa ele atua.', '{"categoria": "framework"}'),
('estrategia', 'Princípio: Persona-first', 'Antes de criar qualquer conteúdo, defina: qual persona? Fernanda (conservadora), Ricardo (premium), Camila (iniciante) ou Leandro (empresário)? Cada uma tem dores, gatilhos e canais diferentes.', '{"categoria": "framework"}'),
('estrategia', 'Princípio: Mix de conteúdo', 'Bloco ideal de 7 pautas: 3-4 técnicos (atração), 2 emocionais (conexão), 1-2 conversão (autoridade/prova). Nunca bloco 100% do mesmo tipo.', '{"categoria": "framework"}'),
('estrategia', 'Princípio: Sequência narrativa', 'Conteúdo deve contar uma história em sequência. Pauta 1: problema. Pauta 2: agitação. Pauta 3: solução. Pauta 4: prova. Pauta 5: oferta.', '{"categoria": "framework"}'),
('estrategia', 'Princípio: Tom Aurora', 'Tom de voz da Autem: simples sem ser simplista, didático sem ser condescendente, técnico sem ser hermético. Sem alarmismo, sem clickbait, sem promessas milagrosas.', '{"categoria": "tom"}'),
('estrategia', 'Princípio: Estrutura de títulos', 'Padrões de título que funcionam: "Como...", "Passo a passo para...", "Descubra...", "Vale a pena?", "X estratégias para...", "O erro que...", "Por que..."', '{"categoria": "tom"}'),
('estrategia', 'Princípio: CTA claro', 'Toda pauta precisa de CTA (call-to-action) específico. Exemplos: "Salve para ler depois", "Comente SE", "Clique no link da bio", "Entre no Telegram", "Agende uma reunião".', '{"categoria": "framework"}'),
('estrategia', 'Princípio: Prova social', 'Use prova social em 20% do conteúdo: depoimentos, cases, UGC, antes e depois. Mostre resultados reais de clientes reais.', '{"categoria": "tatica"}'),
('estrategia', 'Princípio: Quebra de objeção', 'Mapeie objeções de cada persona e crie conteúdo específico para cada: "É arriscado" → conteúdo de segurança. "É caro" → conteúdo de valor. "É complexo" → conteúdo de simplificação.', '{"categoria": "tatica"}'),
('estrategia', 'Princípio: Autoridade técnica', 'Reforce autoridade com dados, certificações, parcerias, anos de mercado, volume sob gestão. Não diga "somos bons", mostre números.', '{"categoria": "tatica"}'),
('estrategia', 'Formato: Carrossel', 'Carrossel: 5-10 slides, primeiro slide é o gancho, último é CTA. Use pouco texto por slide, destaque visual, storytelling sequencial.', '{"categoria": "formato", "canal": "instagram"}'),
('estrategia', 'Formato: Reels', 'Reels: 30-60 segundos, hook nos primeiros 3 segundos, valor no meio, CTA no final. Legendas grandes, áudio trending (opcional), ritmo rápido.', '{"categoria": "formato", "canal": "instagram"}'),
('estrategia', 'Formato: Email', 'Email: assunto que gera curiosidade (não clickbait), primeira linha personalizada, corpo curto (150-300 palavras), CTA único e claro, PS estratégico.', '{"categoria": "formato", "canal": "email"}');

-- Base 3: Personas
INSERT INTO knowledge_documents (base_type, title, content, metadata) VALUES
('personas', 'Persona: Fernanda (Conservadora)', 'Fernanda, 42 anos, professora. Perfil: cautelosa, medo de perder dinheiro, busca segurança acima de tudo. Dores: não entende investimentos, assustada com volatilidade. Gatilhos: proteção, tranquilidade, garantia. Canais preferidos: Instagram (posts educativos), Email (newsletter semanal). Soluções: renda fixa, fundos conservadores, previdência. Objeções: "É seguro?", "Vou perder meu dinheiro?", "Não entendo disso". Como falar: linguagem simples, exemplos do dia a dia, nunca jargão técnico, reforce segurança.', '{"nome": "Fernanda", "perfil": "conservador", "idade": 42, "profissao": "professora"}'),
('personas', 'Persona: Ricardo (Premium)', 'Ricardo, 51 anos, executivo. Perfil: alta renda, busca eficiência fiscal, já investe há anos. Dores: paga muito imposto, quer otimizar patrimônio. Gatilhos: exclusividade, eficiência, resultados. Canais preferidos: Email (relatórios), LinkedIn (nem sempre), eventos presenciais. Soluções: planejamento sucessório, offshore, fundos exclusivos. Objeções: "Vale o custo?", "Tem algo melhor no mercado?", "Já conheço isso". Como falar: dados precisos, análise técnica, proposta customizada, não perca tempo.', '{"nome": "Ricardo", "perfil": "premium", "idade": 51, "profissao": "executivo"}'),
('personas', 'Persona: Camila (Iniciante)', 'Camila, 28 anos, designer. Perfil: jovem, primeira experiência com investimentos, consumidora digital. Dores: não sabe por onde começar, assusta com burocracia. Gatilhos: praticidade, apps fáceis, comunidade. Canais preferidos: Instagram (Reels), TikTok, stories. Soluções: corretora com app bom, primeiro investimento fácil, comunidade. Objeções: "É muito complicado", "Não tenho dinheiro suficiente", "Vou me enrolar". Como falar: vídeos curtos, passo a passo visual, linguagem jovem mas profissional, inspire ação.', '{"nome": "Camila", "perfil": "iniciante", "idade": 28, "profissao": "designer"}'),
('personas', 'Persona: Leandro (Empresário)', 'Leandro, 45 anos, dono de empresa. Perfil: focado em eficiência fiscal, quer proteger patrimônio da empresa. Dores: tributação alta, não sabe separar empresa e pessoa. Gatilhos: economia tributária, proteção patrimonial, planejamento. Canais preferidos: Email (relatórios técnicos), indicações. Soluções: planejamento tributário, holding, proteção patrimonial. Objeções: "Não tenho tempo", "Meu contador já cuida disso", "É muito burocrático". Como falar: direto ao ponto, mostre economia em R$, respeite o tempo dele.', '{"nome": "Leandro", "perfil": "empresario", "idade": 45, "profissao": "empresario"}');

-- Base 4: Resumo Executivo
INSERT INTO knowledge_documents (base_type, title, content, metadata) VALUES
('resumo_executivo', 'Posicionamento da Autem', 'Autem Investimentos: gestora de investimentos focada em planejamento financeiro completo. Posicionamento: parceira de longo prazo, não vendedora de produto. Diferencial: técnica sólida + atendimento humanizado. Não somos: casa de análise, corretora, gestora de fundos exclusivos (mas temos parcerias).', '{"categoria": "posicionamento"}'),
('resumo_executivo', 'Tom de Voz Aurora', 'Tom de voz "Aurora": como o amanhecer - clareza, renovação, esperança concreta. Características: clareza (sem jargão), confiança (sem arrogância), proximidade (sem informalidade demais), propósito (sempre mostrar o porquê).', '{"categoria": "tom"}'),
('resumo_executivo', 'Golden Circle', 'WHY: Democratizar o acesso a investimentos de qualidade. HOW: Educação financeira + planejamento personalizado + gestão técnica. WHAT: Assessoria de investimentos completa, do primeiro real ao patrimônio estruturado.', '{"categoria": "estrategia"}'),
('resumo_executivo', 'Pilares da Marca', '1. Educação antes de venda (ensinar para empoderar). 2. Transparência total (custo, risco, retorno realista). 3. Personalização (não existe cliente igual). 4. Longo prazo (construção de legado, não especulação). 5. Excelência técnica (certificações, análise, due diligence).', '{"categoria": "valores"}'),
('resumo_executivo', 'Essência da Marca', 'Autem = Autonomia + Sistema. Acreditamos que liberdade financeira vem de sistemas, não de sorte. Nossa missão: dar aos clientes o sistema para construir autonomia.', '{"categoria": "essencia"}'),
('resumo_executivo', 'Produtos e Serviços', 'Carteira administrada: gestão completa do patrimônio. Planejamento financeiro: planejamento sucessório, aposentadoria, objetivos. Consultoria: análise pontual, segunda opinião. Curso Autem: educação financeira para iniciantes. Comunidade Telegram: conteúdo diário, networking.', '{"categoria": "produtos"}'),
('resumo_executivo', 'Estratégia de Conteúdo', 'Objetivo: posicionar como referência em investimentos acessíveis. Público: dos iniciantes (Camila) aos sofisticados (Ricardo). Canais: Instagram (visibilidade), Email (nutrição), Telegram (comunidade). Métricas: não só likes, mas leads qualificados e conversões.', '{"categoria": "estrategia"}'),
('resumo_executivo', 'Restrições de Comunicação', 'NUNCA prometer retorno específico. NUNCA criticar concorrentes diretamente. NUNCA usar medo como principal gatilho. NUNCA linguagem de "esquema" ou "golpe". SEMPRE ressalvar que investimentos têm riscos. SEMPRE observar regulação CVM.', '{"categoria": "compliance"}');
